#!/bin/bash
dirs=`ls -rt`

for d in $dirs
do
  if [[ $d == mobill-* ]]; then
    echo "***************************************************************"
    echo "Will now check status of project:  $d";
    cd $d && git status && cd ..;
    echo "***************************************************************"
    echo ""
    echo ""
  fi
done
