#!/bin/bash
dirs=`ls -rt`

for d in $dirs
do
  if [[ $d == mobill-* ]]; then
    echo "***********************************************"
    echo "Will now do a git pull on $d";
    cd $d && git pull && cd ..;
    echo "***********************************************"
    echo ""
    echo ""
  fi
done
